# 🚀 Lab 11: NumPy Arrays and Vector Operations

## 📘 Lab Overview
In this lab, you will learn how to create, manipulate, reshape, and analyze **NumPy arrays** in Python. You will work with both 1D and 2D arrays, perform slicing and indexing, use broadcasting, apply statistical functions, and build a vectorized BMI calculator. By the end of the lab, you will also combine all these ideas in a realistic business-style data analysis example.

### 🤔 What You Are Going to Do
In simple words, this lab teaches you how to work with data in **bulk** instead of one value at a time. Imagine trying to add 1 to a thousand different numbers one by one—it takes forever! NumPy helps us store numbers in 'arrays' (like organized lists) and then perform fast operations on all of them at once. This is the superpower behind data science and machine learning.

## 🎯 Objectives
By the end of this lab, you will be able to:
* Create and manipulate 1D and 2D NumPy arrays
* Perform array slicing and indexing operations
* Reshape arrays to different dimensions
* Apply broadcasting principles for array operations
* Use statistical functions to analyze data
* Vectorize mathematical formulas for efficient computation
* Calculate Body Mass Index (BMI) using vectorized operations

## 🧰 Prerequisites & ⚙️ Environment Setup
Before starting, ensure you have a basic understanding of Python. Google Colab comes with NumPy pre-installed, but we will verify it below.

In [1]:
# Task 1: Verify NumPy Installation
import numpy as np

# We print the version to ensure the library is loaded and ready
print("NumPy version:", np.__version__)

# If you ever get a 'ModuleNotFoundError', you would run:
# %pip install numpy

NumPy version: 2.0.2


## 🧪 Task 2: Creating 1D and 2D NumPy Arrays

### 💡 Why this matters
Before we can analyze data, we need to get it into a NumPy format. We can turn standard Python lists into arrays or generate arrays of zeros, ones, or random numbers instantly.

In [2]:
# Subtask 2.1: Creating 1D Arrays
print("=== Creating 1D Arrays ===")

# Method 1: From Python list - turning basic data into a NumPy array
ages = np.array([25, 30, 35, 40, 45])
print("Ages array:", ages)
print("Data type:", ages.dtype) # Tells us what kind of numbers are inside
print("Shape:", ages.shape)     # Tells us the size of the array

# Method 2: Using arange - creates a range of numbers (start, stop, step)
numbers = np.arange(0, 10, 2)
print("Numbers using arange:", numbers)

# Method 3: Using linspace - creates 5 evenly spaced values between 20 and 40
temperatures = np.linspace(20, 40, 5)
print("Temperatures using linspace:", temperatures)

# Method 4: Arrays filled with specific values - useful for initializing models
zeros_array = np.zeros(5)
ones_array = np.ones(5)
full_array = np.full(5, 7.5)

print("Zeros array:", zeros_array)
print("Ones array:", ones_array)
print("Full array (7.5):", full_array)

=== Creating 1D Arrays ===
Ages array: [25 30 35 40 45]
Data type: int64
Shape: (5,)
Numbers using arange: [0 2 4 6 8]
Temperatures using linspace: [20. 25. 30. 35. 40.]
Zeros array: [0. 0. 0. 0. 0.]
Ones array: [1. 1. 1. 1. 1.]
Full array (7.5): [7.5 7.5 7.5 7.5 7.5]


In [3]:
# Subtask 2.2: Creating 2D Arrays
print("\n=== Creating 2D Arrays ===")

# Method 1: From nested Python lists (Rows and Columns)
student_scores = np.array([
    [85, 92, 78],
    [90, 88, 95],
    [76, 84, 89]
])

print("Student scores (2D array):")
print(student_scores)
print("Shape:", student_scores.shape) # Rows, Columns
print("Dimensions:", student_scores.ndim)

# Method 2: Using reshape - turning a line of numbers into a grid
linear_data = np.arange(12)
matrix_data = linear_data.reshape(3, 4)

print("\nOriginal linear data:", linear_data)
print("Reshaped to 3x4 matrix:")
print(matrix_data)

# Method 3: Creating special 2D arrays
identity_matrix = np.eye(3) # Square matrix with 1s on the diagonal
random_matrix = np.random.rand(2, 3) # Random numbers between 0 and 1

print("\nIdentity matrix (3x3):")
print(identity_matrix)

print("\nRandom matrix (2x3):")
print(random_matrix)


=== Creating 2D Arrays ===
Student scores (2D array):
[[85 92 78]
 [90 88 95]
 [76 84 89]]
Shape: (3, 3)
Dimensions: 2

Original linear data: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random matrix (2x3):
[[0.75731838 0.43913929 0.20113749]
 [0.66997429 0.0309566  0.35938518]]


## 🧪 Task 3: Array Slicing Operations

### 💡 Why this matters
Slicing lets us 'zoom in' on specific parts of our data, like looking at just the weekend temperatures or the first subject scores for every student.

In [4]:
# Subtask 3.1: 1D Array Slicing
print("\n=== 1D Array Slicing ===")

# Sample data: daily temperatures for a week
daily_temps = np.array([22.5, 24.1, 26.3, 28.7, 25.9, 23.4, 21.8])
print("Daily temperatures:", daily_temps)

# Basic slicing [start:stop:step]
print("First 3 days:", daily_temps[:3])
print("Last 3 days:", daily_temps[-3:])
print("Middle days (index 2-4):", daily_temps[2:5])
print("Every other day:", daily_temps[::2])

# Boolean indexing - filtering data based on a condition
hot_days = daily_temps > 25
print("Days with temperature > 25°C:", daily_temps[hot_days])

# Fancy indexing - picking specific items by their index
weekend_indices = [0, 6]  # Sunday and Saturday
print("Weekend temperatures:", daily_temps[weekend_indices])


=== 1D Array Slicing ===
Daily temperatures: [22.5 24.1 26.3 28.7 25.9 23.4 21.8]
First 3 days: [22.5 24.1 26.3]
Last 3 days: [25.9 23.4 21.8]
Middle days (index 2-4): [26.3 28.7 25.9]
Every other day: [22.5 26.3 25.9 21.8]
Days with temperature > 25°C: [26.3 28.7 25.9]
Weekend temperatures: [22.5 21.8]


In [5]:
# Subtask 3.2: 2D Array Slicing
print("\n=== 2D Array Slicing ===")

# 4 students (rows) in 3 subjects (columns)
test_scores = np.array([
    [85, 92, 78],  # Student 1
    [90, 88, 95],  # Student 2
    [76, 84, 89],  # Student 3
    [88, 91, 87]   # Student 4
])

# Row slicing [rows, columns]
print("First 2 students' scores:")
print(test_scores[:2])

# Column slicing - Use ':' to select all rows, then specify the column index
print("All students' first subject scores:", test_scores[:, 0])
print("All students' last subject scores:", test_scores[:, -1])

# Subarray slicing - selecting a smaller grid from the big grid
print("First 2 students, first 2 subjects:")
print(test_scores[:2, :2])

# Individual element access - [row, col]
print("Student 3, Subject 2 score:", test_scores[2, 1])


=== 2D Array Slicing ===
First 2 students' scores:
[[85 92 78]
 [90 88 95]]
All students' first subject scores: [85 90 76 88]
All students' last subject scores: [78 95 89 87]
First 2 students, first 2 subjects:
[[85 92]
 [90 88]]
Student 3, Subject 2 score: 84


## 🧪 Task 4: Array Reshaping Operations

### 💡 Why this matters
Data isn't always in the shape we need. Reshaping allows us to change how data is organized (e.g., from a flat list to a 3D volume) without changing the values themselves.

In [6]:
# Subtask 4.1: Basic Reshaping
print("\n=== Array Reshaping ===")

original_array = np.arange(24)
print("Original array (24 elements):", original_array)

# Change to 4 rows and 6 columns
reshaped_2d = original_array.reshape(4, 6)
print("\nReshaped to 4x6:")
print(reshaped_2d)

# Change to 3D: 2 layers, 3 rows, 4 columns
reshaped_3d = original_array.reshape(2, 3, 4)
print("\nReshaped to 2x3x4:")
print(reshaped_3d)

# Automatic dimension calculation using -1 (NumPy figures out the columns)
auto_reshape = original_array.reshape(8, -1)
print("\nAuto-reshaped to 8 rows:")
print(auto_reshape)


=== Array Reshaping ===
Original array (24 elements): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Reshaped to 4x6:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Reshaped to 2x3x4:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Auto-reshaped to 8 rows:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [7]:
# Subtask 4.2: Flattening and Transposing
print("\n=== Flattening and Transposing ===")

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Flattening - squashing a grid back into a single line
flattened = matrix.flatten()
print("Flattened array:", flattened)

# Transposing - swapping rows with columns
transposed = matrix.T
print("Transposed matrix:")
print(transposed)


=== Flattening and Transposing ===
Flattened array: [1 2 3 4 5 6 7 8 9]
Transposed matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 🧪 Task 5: Broadcasting Operations

### 💡 Why this matters
Broadcasting is how NumPy handles operations between arrays of different sizes. It 'stretches' the smaller array to fit the larger one so you don't have to write loops.

In [8]:
# Subtask 5.1: Understanding Broadcasting
print("\n=== Broadcasting Operations ===")

array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Scalar broadcasting - 10 is added to every single cell
result_scalar = array_2d + 10
print("\nAdding scalar 10 to all elements:")
print(result_scalar)

# 1D array broadcasting - [1, 2, 3] is added to every row
array_1d = np.array([1, 2, 3])
result_1d = array_2d + array_1d
print("\nAdding 1D array [1, 2, 3] to each row:")
print(result_1d)


=== Broadcasting Operations ===

Adding scalar 10 to all elements:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Adding 1D array [1, 2, 3] to each row:
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [9]:
# Subtask 5.2: Practical Broadcasting: Sales Analysis
print("\n=== Practical Broadcasting: Sales Analysis ===")

# Monthly sales data for 3 products across 4 months
monthly_sales = np.array([
    [1000, 1200, 1100, 1300],  # Product A
    [800, 900, 950, 1000],     # Product B
    [1500, 1400, 1600, 1550]   # Product C
])

# Apply 10% discount (broadcasting a scalar)
discount_rate = 0.10
discounted_sales = monthly_sales * (1 - discount_rate)
print("\nSales after 10% discount:")
print(discounted_sales)

# Different discount rates for each product (broadcasting a column)
# Product A: 5%, Product B: 10%, Product C: 15%
product_discounts = np.array([[0.05], [0.10], [0.15]])
variable_discounts = monthly_sales * (1 - product_discounts)
print("\nSales with variable discounts per product:")
print(variable_discounts)


=== Practical Broadcasting: Sales Analysis ===

Sales after 10% discount:
[[ 900. 1080.  990. 1170.]
 [ 720.  810.  855.  900.]
 [1350. 1260. 1440. 1395.]]

Sales with variable discounts per product:
[[ 950.  1140.  1045.  1235. ]
 [ 720.   810.   855.   900. ]
 [1275.  1190.  1360.  1317.5]]


## 🧪 Task 6: Statistical Functions

### 💡 Why this matters
Instead of calculating averages manually, NumPy provides instant functions to find the mean, median, and spread (standard deviation) of your data.

In [10]:
# Subtask 6.1 & 6.2: Statistical Operations
print("\n=== Statistical Functions ===")

test_scores = np.array([
    [85, 92, 78, 88],
    [90, 88, 95, 87],
    [76, 84, 89, 91],
    [88, 91, 87, 85]
])

# Overall Statistics
print("Mean score:", np.mean(test_scores))
print("Standard deviation:", np.std(test_scores))

# Axis-Specific Statistics
# axis=1 means 'across the rows' (Stats per student)
print("\nMean scores per student (rows):", np.mean(test_scores, axis=1))

# axis=0 means 'down the columns' (Stats per test)
print("Mean scores per test (columns):", np.mean(test_scores, axis=0))

print("\n75th percentile:", np.percentile(test_scores, 75))


=== Statistical Functions ===
Mean score: 87.125
Standard deviation: 4.715334028465004

Mean scores per student (rows): [85.75 90.   85.   87.75]
Mean scores per test (columns): [84.75 88.75 87.25 87.75]

75th percentile: 90.25


## 🧪 Task 7: Vectorizing Mathematical Formulas (BMI Calculator)

### 💡 Why this matters
Vectorization allows us to apply a formula to thousands of data points at once. We'll calculate BMI for 6 people without a single 'for' loop.

In [11]:
# Subtask 7.1: BMI Calculation Using Vectorization
print("\n=== BMI Calculator Using Vectorization ===")

heights = np.array([1.75, 1.68, 1.82, 1.65, 1.78, 1.70])
weights = np.array([70, 65, 85, 55, 80, 68])

# Vectorized Formula: BMI = kg / m^2
bmi_values = weights / (heights ** 2)
print("BMI values:", np.round(bmi_values, 2))

# Categorizing BMI using Boolean Indexing
def categorize_bmi(bmi_array):
    categories = np.empty(bmi_array.shape, dtype='<U15')
    categories[bmi_array < 18.5] = 'Underweight'
    categories[(bmi_array >= 18.5) & (bmi_array < 25)] = 'Normal'
    categories[(bmi_array >= 25) & (bmi_array < 30)] = 'Overweight'
    categories[bmi_array >= 30] = 'Obese'
    return categories

bmi_categories = categorize_bmi(bmi_values)
print("BMI categories:", bmi_categories)

# Subtask 7.2: Individual Report
print("\n--- Individual BMI Report ---")
for i in range(len(heights)):
    print(f"Person {i+1}: Height={heights[i]}m, Weight={weights[i]}kg, BMI={bmi_values[i]:.2f} ({bmi_categories[i]})")


=== BMI Calculator Using Vectorization ===
BMI values: [22.86 23.03 25.66 20.2  25.25 23.53]
BMI categories: ['Normal' 'Normal' 'Overweight' 'Normal' 'Overweight' 'Normal']

--- Individual BMI Report ---
Person 1: Height=1.75m, Weight=70kg, BMI=22.86 (Normal)
Person 2: Height=1.68m, Weight=65kg, BMI=23.03 (Normal)
Person 3: Height=1.82m, Weight=85kg, BMI=25.66 (Overweight)
Person 4: Height=1.65m, Weight=55kg, BMI=20.20 (Normal)
Person 5: Height=1.78m, Weight=80kg, BMI=25.25 (Overweight)
Person 6: Height=1.7m, Weight=68kg, BMI=23.53 (Normal)


## 🧪 Task 8: Comprehensive Example - Data Analysis

### 💡 Why this matters
This final task combines everything: creating data, broadcasting variations, and calculating growth rates.

In [12]:
# Subtask 8.1: Complete Data Analysis Workflow
print("\n=== Comprehensive Data Analysis Example ===")

np.random.seed(42)  # Ensures the 'random' numbers are the same every time we run

# Base monthly sales for 4 products
base_sales = np.array([1000, 800, 1200, 600])
# Random variations for 12 months (4 rows x 12 columns)
monthly_variation = np.random.normal(0, 100, (4, 12))

# Using broadcasting to add base sales to each month's variation
sales_data = base_sales.reshape(-1, 1) + monthly_variation
sales_data = np.maximum(sales_data, 0) # No negative sales allowed!

# Analysis
print(f"Total annual sales: ${np.sum(sales_data):,.0f}")

# Growth analysis (Comparing first 3 months vs last 3 months)
q1_sales = np.mean(sales_data[:, :3], axis=1)
q4_sales = np.mean(sales_data[:, -3:], axis=1)
growth_rate = ((q4_sales - q1_sales) / q1_sales) * 100

print("\n--- Growth Analysis (Q1 vs Q4) ---")
for i, growth in enumerate(growth_rate):
    print(f"Product {i+1}: {growth:+.1f}% growth")


=== Comprehensive Data Analysis Example ===
Total annual sales: $42,215

--- Growth Analysis (Q1 vs Q4) ---
Product 1: -4.5% growth
Product 2: +8.8% growth
Product 3: +0.4% growth
Product 4: +19.8% growth


## ✅ Verification Checklist
* [ ] Did you successfully import NumPy?
* [ ] Did you create 1D and 2D arrays?
* [ ] Did you extract data using slicing?
* [ ] Did you reshape a 1D array into a 2D matrix?
* [ ] Did you calculate summary statistics (mean, std)?
* [ ] Did the BMI calculator produce the correct categories?

## 🛠 Troubleshooting
* **Import Error**: If you see `ModuleNotFoundError`, run `%pip install numpy`.
* **Shape Mismatch**: If adding arrays fails, use `print(array.shape)` to check if they are compatible for broadcasting.
* **Reshape Error**: Remember that `rows * columns` must equal the total number of elements in the original array.

## 📚 Key Takeaways
1. **Vectorization**: NumPy operations happen all at once, making them much faster than Python loops.
2. **Broadcasting**: NumPy can smartly align arrays of different sizes.
3. **Slicing**: You can grab any row, column, or block of data easily using `[row, col]` syntax.

## Conclusion
Congratulations! You've mastered the basics of NumPy. These tools are the foundation for nearly all data science work in Python.